#pragma once
#include<windows.h>
#include<errno.h>
#include<stdio.h>
#include<time.h>
#include<stdlib.h>
#include<string.h>
#include<ctype.h>
#include<math.h>
#include"TBdefine.h"
#include"prototype.h"
#include"Text.h"
#include"GeneralFunctions.h"
#include"TBglobal.h"
#include"Data.h"
#include"Class.h"
#include"TBAI.h"
#include"Config.h"
#include"TBfunc.h"
#include"shop.h"